version: "3"

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
  
  # frontend:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./client:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
   
  mongodb:
    image: mongo
    ports:
      - "27018:27017"