version: "3"

services:
  backend:
    build: 
      context: ./server
      dockerfile: Dockerfile.prod
      args: 
        - NODE_ENV=production
    environment:
    - NODE_ENV=production
  
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
    ports:
      - 8080:80
    environment:
      - NODE_ENV=production